apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_CONNECT: bW9uZ29kOi8vbW9uZ28tc2VydmljZS91YmVy
  JWT_SECRET: MTIzNDU2b3Bvan4yMTM5MG9tZHM=
  GOOGLE_MAPS_API: QUl6YVN5QzZQWTh2R1dtbC05SXh2ZVN4ellwZEhuVUxvTGNCUXM=
  VITE_GOOGLE_MAPS_API_KEY: QUl6YVN5QzZQWTh2R1dtbC05SXh2ZVN4ellwZEhuVUxvTGNCUXM=

